package mystructure;

/**
 * Created by Fabrice on 12/09/16.
 */

public enum ExpTechniquesEnum {

    XRAY_DIFFRACTION,
    SOLUTION_NMR,
    SOLID_STATE_NMR,
    ELECTRON_MICROSCOPY,
    ELECTRON_CRYSTALLOGRAPHY,
    FIBER_DIFFRACTION,
    NEUTRON_DIFFRACTION,
    POWDER_DIFFRACTION,
    SOLUTION_SCATTERING,
    UNDEFINED;
}